; /*********************************************************
;  dsk1_wrseq.asm mk_dskcallversion.sh によって自動生成されるファイルなので
;  書き換えないでください。

;   Do not rewrite dsk1_wrseq.asm as this file is
;  automatically generated by mk_dskcallversion.sh.

;  *********************************************************/

    include "msxlib/asm/msxdos.inc"


    SECTION code_user
    PUBLIC dsk1_wrseq
    PUBLIC _dsk1_wrseq
    PUBLIC ___dsk1_wrseq

; /* シーケンシャルな書き込み(FCB) */
; uint8_t __LIB__ dsk1_wrseq(MSX_FCB *fcb) __smallc;
dsk1_wrseq:
_dsk1_wrseq:
___dsk1_wrseq:
    ld hl,2
    add hl,sp

    ld e,(hl)
    inc hl
    ld d,(hl)

    ld c,_WRSEQ
    jp BDOS_DSK