; /*********************************************************
;  dsk1_wrabs.asm mk_dskcallversion.sh によって自動生成されるファイルなので
;  書き換えないでください。

;   Do not rewrite dsk1_wrabs.asm as this file is
;  automatically generated by mk_dskcallversion.sh.

;  *********************************************************/

    include "msxlib/asm/msxdos.inc"


    SECTION code_user
    PUBLIC dsk1_wrabs
    PUBLIC _dsk1_wrabs
    PUBLIC ___dsk1_wrabs

; /* アブソリュートなセクタ書き込み */
; uint8_t __LIB__ dsk1_wrabs(uint8_t drv, uint16_t sec, uint8_t num);
;
;   sp + 2  num
;   sp + 4  sec
;   sp + 6  drv
dsk1_wrabs:
_dsk1_wrabs:
___dsk1_wrabs:
    ld hl,2
    add hl,sp

    ld a,(hl)
    inc hl
    inc hl

    ld e,(hl)
    inc hl
    ld d,(hl)
    inc hl

    ld l,(hl)
    
    ld h,a

    ld c,_WRABS
    call BDOS_DSK
    ld l,a
    ret
