; /*********************************************************
;  dsk1_dirio.asm mk_dskcallversion.sh によって自動生成されるファイルなので
;  書き換えないでください。

;   Do not rewrite dsk1_dirio.asm as this file is
;  automatically generated by mk_dskcallversion.sh.

;  *********************************************************/

    include "msxlib/asm/msxdos.inc"


    SECTION code_user
    PUBLIC dsk1_dirio
    PUBLIC _dsk1_dirio
    PUBLIC ___dsk1_dirio


; /* 直接コンソールI/O */
; char dsk1_dirio(char code);
dsk1_dirio:
_dsk1_dirio:
___dsk1_dirio:
    ld hl,2
    add hl,sp

    ld e,(hl)

    ld c,_DIRIO
    jp BDOS_DSK
