; /*********************************************************
;  dsk1_term0.asm mk_dskcallversion.sh によって自動生成されるファイルなので
;  書き換えないでください。

;   Do not rewrite dsk1_term0.asm as this file is
;  automatically generated by mk_dskcallversion.sh.

;  *********************************************************/

    include "msxlib/asm/msxdos.inc"


    SECTION code_user
    PUBLIC dsk1_term0
    PUBLIC _dsk1_term0
    PUBLIC ___dsk1_term0


; /* プログラムの終了 */
; void __LIB__ dsk1_term0(void) __smallc;
dsk1_term0:
_dsk1_term0:
___dsk1_term0:
    ld c,_TERM0
    jp BDOS_DSK
