; /*********************************************************
;  dsk1_const.asm mk_dskcallversion.sh によって自動生成されるファイルなので
;  書き換えないでください。

;   Do not rewrite dsk1_const.asm as this file is
;  automatically generated by mk_dskcallversion.sh.

;  *********************************************************/

    include "msxlib/asm/msxdos.inc"


    SECTION code_user
    PUBLIC dsk1_const
    PUBLIC _dsk1_const
    PUBLIC ___dsk1_const


; /* コンソールステータス */
; uint8_t dsk1_const();
dsk1_const:
_dsk1_const:
___dsk1_const:
    ld c,_CONST
    jp BDOS_DSK
