; /*********************************************************
;  dsk1_gtime.asm mk_dskcallversion.sh によって自動生成されるファイルなので
;  書き換えないでください。

;   Do not rewrite dsk1_gtime.asm as this file is
;  automatically generated by mk_dskcallversion.sh.

;  *********************************************************/

    include "msxlib/asm/msxdos.inc"


    SECTION code_user
    PUBLIC dsk1_gtime
    PUBLIC _dsk1_gtime
    PUBLIC ___dsk1_gtime

; /* 時間の取得 */
; void __LIB__ dsk1_gtime(uint8_t *hour, uint8_t *min, uint8_t *sec);
;
;   sp + 2  *sec
;   sp + 4  *min
;   sp + 6  *hour
dsk1_gtime:
_dsk1_gtime:
___dsk1_gtime:
    ld c,_GTIME
    call BDOS_DSK

    ld b,h
    ld c,l
    ld a,d

    ld hl,2
    add hl,sp

    ; sec
    ld e,(hl)
    inc hl
    ld d,(hl)
    inc hl

    ld (de),a

    ; min
    ld e,(hl)
    inc hl
    ld d,(hl)
    inc hl

    ex hl,de
    ld (hl),c
    ex hl,de

    ld e,(hl)
    inc hl
    ld d,(hl)

    ex hl,de
    ld (hl),b

    ret
