; /*********************************************************
;  dsk1_auxin.asm mk_dskcallversion.sh によって自動生成されるファイルなので
;  書き換えないでください。

;   Do not rewrite dsk1_auxin.asm as this file is
;  automatically generated by mk_dskcallversion.sh.

;  *********************************************************/

    include "msxlib/asm/msxdos.inc"


    SECTION code_user
    PUBLIC dsk1_auxin
    PUBLIC _dsk1_auxin
    PUBLIC ___dsk1_auxin

; /* 補助入力 */
; uint8_t __LIB__ dsk1_auxin(void) __smallc;
dsk1_auxin:
_dsk1_auxin:
___dsk1_auxin:
    ld c,_AUXIN
    jp BDOS_DSK
