; /*********************************************************
;  dsk1_dirin.asm mk_dskcallversion.sh によって自動生成されるファイルなので
;  書き換えないでください。

;   Do not rewrite dsk1_dirin.asm as this file is
;  automatically generated by mk_dskcallversion.sh.

;  *********************************************************/

    include "msxlib/asm/msxdos.inc"


    SECTION code_user
    PUBLIC dsk1_dirin
    PUBLIC _dsk1_dirin
    PUBLIC ___dsk1_dirin

; /* 直接コンソール入力 */
; uint8_t __LIB__ dsk1_dirin(void) __smallc;
dsk1_dirin:
_dsk1_dirin:
___dsk1_dirin:
    ld c,_DIRIN
    jp BDOS_DSK
