; /*********************************************************
;  dsk1_cpmver.asm mk_dskcallversion.sh によって自動生成されるファイルなので
;  書き換えないでください。

;   Do not rewrite dsk1_cpmver.asm as this file is
;  automatically generated by mk_dskcallversion.sh.

;  *********************************************************/

    include "msxlib/asm/msxdos.inc"


    SECTION code_user
    PUBLIC dsk1_cpmver
    PUBLIC _dsk1_cpmver
    PUBLIC ___dsk1_cpmver

; /* バージョン番号の取得 */
; uint16_t __LIB__ dsk1_cpmver(void) __smallc;
dsk1_cpmver:
_dsk1_cpmver:
___dsk1_cpmver:
    ld c,_CPMVER
    jp BDOS_DSK
