; /*********************************************************
;  dsk1_snext.asm mk_dskcallversion.sh によって自動生成されるファイルなので
;  書き換えないでください。

;   Do not rewrite dsk1_snext.asm as this file is
;  automatically generated by mk_dskcallversion.sh.

;  *********************************************************/

    include "msxlib/asm/msxdos.inc"


    SECTION code_user
    PUBLIC dsk1_snext
    PUBLIC _dsk1_snext
    PUBLIC ___dsk1_snext

; /* 次のエントリの検索(FCB) */
; uint8_t __LIB__ dsk1_snext(void) __smallc;

dsk1_snext:
_dsk1_snext:
___dsk1_snext:

    ld c,_SNEXT
    jp BDOS_DSK