; /*********************************************************
;  dsk1_fren.asm mk_dskcallversion.sh によって自動生成されるファイルなので
;  書き換えないでください。

;   Do not rewrite dsk1_fren.asm as this file is
;  automatically generated by mk_dskcallversion.sh.

;  *********************************************************/

    include "msxlib/asm/msxdos.inc"


    SECTION code_user
    PUBLIC dsk1_fren
    PUBLIC _dsk1_fren
    PUBLIC ___dsk1_fren


; /* ファイル名の変更(FCB) */
; uint8_t __LIB__ dsk1_fren(void *fcb) __smallc;
dsk1_fren:
_dsk1_fren:
___dsk1_fren:
    ld hl,2
    add hl,sp

    ld e,(hl)
    inc hl
    ld d,(hl)

    ld c,_FREN
    jp BDOS_DSK
