; /*********************************************************
;  dsk1_setrnd.asm mk_dskcallversion.sh によって自動生成されるファイルなので
;  書き換えないでください。

;   Do not rewrite dsk1_setrnd.asm as this file is
;  automatically generated by mk_dskcallversion.sh.

;  *********************************************************/

    include "msxlib/asm/msxdos.inc"


    SECTION code_user
    PUBLIC dsk1_setrnd
    PUBLIC _dsk1_setrnd
    PUBLIC ___dsk1_setrnd


; /* ランダムレコードの設定[FCB] */
; void __LIB__ dsk1_setrnd(MSX_FCB *fcb) __smallc;
dsk1_setrnd:
_dsk1_setrnd:
___dsk1_setrnd:
    ld hl,2
    add hl,sp

    ld e,(hl)
    inc hl
    ld d,(hl)

    ld c,_SETRND
    jp BDOS_DSK
