; /*********************************************************
;  dsk1_conout.asm mk_dskcallversion.sh によって自動生成されるファイルなので
;  書き換えないでください。

;   Do not rewrite dsk1_conout.asm as this file is
;  automatically generated by mk_dskcallversion.sh.

;  *********************************************************/

    include "msxlib/asm/msxdos.inc"


    SECTION code_user
    PUBLIC dsk1_conout
    PUBLIC _dsk1_conout
    PUBLIC ___dsk1_conout


; /* コンソールに1文字出力する */
; void dsk1_conout(char ch);
dsk1_conout:
_dsk1_conout:
___dsk1_conout:
    ld hl,2
    add hl,sp

    ld e,(hl)
    
    ld c,_CONOUT
    jp BDOS_DSK
