; /*********************************************************
;  dsk1_dskrst.asm mk_dskcallversion.sh によって自動生成されるファイルなので
;  書き換えないでください。

;   Do not rewrite dsk1_dskrst.asm as this file is
;  automatically generated by mk_dskcallversion.sh.

;  *********************************************************/

    include "msxlib/asm/msxdos.inc"


    SECTION code_user
    PUBLIC dsk1_dskrst
    PUBLIC _dsk1_dskrst
    PUBLIC ___dsk1_dskrst

; /* ディスクリセット */
; void __LIB__ dsk1_dskrst(void) __smallc;
dsk1_dskrst:
_dsk1_dskrst:
___dsk1_dskrst:
    ld c,_DSKRST
    jp BDOS_DSK
