; /*********************************************************
;  dsk1_lstout.asm mk_dskcallversion.sh によって自動生成されるファイルなので
;  書き換えないでください。

;   Do not rewrite dsk1_lstout.asm as this file is
;  automatically generated by mk_dskcallversion.sh.

;  *********************************************************/

    include "msxlib/asm/msxdos.inc"


    SECTION code_user
    PUBLIC dsk1_lstout
    PUBLIC _dsk1_lstout
    PUBLIC ___dsk1_lstout

; /* プリンタ出力 */
; void __LIB__ dsk1_lstout(char ch) __smallc;
dsk1_lstout:
_dsk1_lstout:
___dsk1_lstout:
    ld hl,2
    add hl,sp

    ld e,(hl)
    
    ld c,_LSTOUT
    jp BDOS_DSK
