; /*********************************************************
;  dsk1_sdate.asm mk_dskcallversion.sh によって自動生成されるファイルなので
;  書き換えないでください。

;   Do not rewrite dsk1_sdate.asm as this file is
;  automatically generated by mk_dskcallversion.sh.

;  *********************************************************/

    include "msxlib/asm/msxdos.inc"


    SECTION code_user
    PUBLIC dsk1_sdate
    PUBLIC _dsk1_sdate
    PUBLIC ___dsk1_sdate


; /* 日付の設定 */
; uint8_t __LIB__ dsk1_sdate(uint16_t year, uint8_t month, uint8_t mday);
dsk1_sdate:
_dsk1_sdate:
___dsk1_sdate:
    ld hl,2
    add hl,sp

    ld e,(hl)
    inc hl
    inc hl

    ld d,(hl)
    inc hl
    inc hl

    ld c,(hl)
    inc hl
    ld b,(hl)

    ld h,b
    ld l,c

    ld c, _SDATE
    call BDOS_DSK

    ld l,a
    ret
