; /*********************************************************
;  dsk1_fsize.asm mk_dskcallversion.sh によって自動生成されるファイルなので
;  書き換えないでください。

;   Do not rewrite dsk1_fsize.asm as this file is
;  automatically generated by mk_dskcallversion.sh.

;  *********************************************************/

    include "msxlib/asm/msxdos.inc"


    SECTION code_user
    PUBLIC dsk1_fsize
    PUBLIC _dsk1_fsize
    PUBLIC ___dsk1_fsize

; /* ファイルサイズの取得(FCB) */
; uint8_t __LIB__ dsk1_fsize(MSX_FCB *fcb) __smallc;
dsk1_fsize:
_dsk1_fsize:
___dsk1_fsize:
    ld hl,2
    add hl,sp

    ld e,(hl)
    inc hl
    ld d,(hl)

    ld c,_FSIZE
    jp BDOS_DSK
