; /*********************************************************
;  dsk1_innoe.asm mk_dskcallversion.sh によって自動生成されるファイルなので
;  書き換えないでください。

;   Do not rewrite dsk1_innoe.asm as this file is
;  automatically generated by mk_dskcallversion.sh.

;  *********************************************************/

    include "msxlib/asm/msxdos.inc"


    SECTION code_user
    PUBLIC dsk1_innoe
    PUBLIC _dsk1_innoe
    PUBLIC ___dsk1_innoe

; /* エコーなしコンソール入力 */
; uint8_t __LIB__ dsk1_innoe(void) __smallc;
dsk1_innoe:
_dsk1_innoe:
___dsk1_innoe:
    ld c,_INNOE
    jp BDOS_DSK
