; /*********************************************************
;  dsk1_fmake.asm mk_dskcallversion.sh によって自動生成されるファイルなので
;  書き換えないでください。

;   Do not rewrite dsk1_fmake.asm as this file is
;  automatically generated by mk_dskcallversion.sh.

;  *********************************************************/

    include "msxlib/asm/msxdos.inc"


    SECTION code_user
    PUBLIC dsk1_fmake
    PUBLIC _dsk1_fmake
    PUBLIC ___dsk1_fmake


; /* ファイルの作成 */
; int8_t dsk1_fmake(void *fcb);
dsk1_fmake:
_dsk1_fmake:
___dsk1_fmake:
    ld hl,2
    add hl,sp

    ld e,(hl)
    inc hl
    ld d,(hl)

    ld c,_FMAKE
    jp BDOS_DSK
