; /*********************************************************
;  dsk1_rdabs.asm mk_dskcallversion.sh によって自動生成されるファイルなので
;  書き換えないでください。

;   Do not rewrite dsk1_rdabs.asm as this file is
;  automatically generated by mk_dskcallversion.sh.

;  *********************************************************/

    include "msxlib/asm/msxdos.inc"


    SECTION code_user
    PUBLIC dsk1_rdabs
    PUBLIC _dsk1_rdabs
    PUBLIC ___dsk1_rdabs

; /* アブソリュートなセクタ読み込み */
; uint8_t __LIB__ dsk1_rdabs(uint8_t drv, uint16_t sec, uint8_t num);
;
;   sp + 2  num
;   sp + 4  sec
;   sp + 6  drv
dsk1_rdabs:
_dsk1_rdabs:
___dsk1_rdabs:
    ld hl,2
    add hl,sp

    ld a,(hl)
    inc hl
    inc hl

    ld e,(hl)
    inc hl
    ld d,(hl)
    inc hl

    ld l,(hl)
    
    ld h,a

    ld c,_RDABS
    call BDOS_DSK
    ld l,a
    ret
