; /*********************************************************
;  dsk1_sfirst.asm mk_dskcallversion.sh によって自動生成されるファイルなので
;  書き換えないでください。

;   Do not rewrite dsk1_sfirst.asm as this file is
;  automatically generated by mk_dskcallversion.sh.

;  *********************************************************/

    include "msxlib/asm/msxdos.inc"


    SECTION code_user
    PUBLIC dsk1_sfirst
    PUBLIC _dsk1_sfirst
    PUBLIC ___dsk1_sfirst

; /* 最初のエントリの検索(FCB) */
; uint8_t __LIB__ dsk1_sfirst(void *fcb) __smallc;

dsk1_sfirst:
_dsk1_sfirst:
___dsk1_sfirst:
    ; fcbを取り出す
    ld hl,2
    add hl,sp

    ld e,(hl)
    inc hl
    ld d,(hl)

    ld c,_SFIRST
    jp BDOS_DSK