; /*********************************************************
;  dsk1_fopen.asm mk_dskcallversion.sh によって自動生成されるファイルなので
;  書き換えないでください。

;   Do not rewrite dsk1_fopen.asm as this file is
;  automatically generated by mk_dskcallversion.sh.

;  *********************************************************/

    include "msxlib/asm/msxdos.inc"


    SECTION code_user
    PUBLIC dsk1_fopen
    PUBLIC _dsk1_fopen
    PUBLIC ___dsk1_fopen


; /* ファイルオープン */
; int8_t dsk1_fmake(void *fcb);
dsk1_fopen:
_dsk1_fopen:
___dsk1_fopen:
    ld hl,2
    add hl,sp

    ld e,(hl)
    inc hl
    ld d,(hl)

    ld c,_FOPEN
    jp BDOS_DSK
