; /*********************************************************
;  dsk1_rdseq.asm mk_dskcallversion.sh によって自動生成されるファイルなので
;  書き換えないでください。

;   Do not rewrite dsk1_rdseq.asm as this file is
;  automatically generated by mk_dskcallversion.sh.

;  *********************************************************/

    include "msxlib/asm/msxdos.inc"


    SECTION code_user
    PUBLIC dsk1_rdseq
    PUBLIC _dsk1_rdseq
    PUBLIC ___dsk1_rdseq


; /* シーケンシャル読み込み(FCB) */
; uint8_t __LIB__ dsk1_rdseq(void *fcb) __smallc;

dsk1_rdseq:
_dsk1_rdseq:
___dsk1_rdseq:
    ld hl,2
    add hl,sp

    ld e,(hl)
    inc hl
    ld d,(hl)

    ld c,_RDSEQ
    jp BDOS_DSK
