; /*********************************************************
;  dsk1_rdrnd.asm mk_dskcallversion.sh によって自動生成されるファイルなので
;  書き換えないでください。

;   Do not rewrite dsk1_rdrnd.asm as this file is
;  automatically generated by mk_dskcallversion.sh.

;  *********************************************************/

    include "msxlib/asm/msxdos.inc"


    SECTION code_user
    PUBLIC dsk1_rdrnd
    PUBLIC _dsk1_rdrnd
    PUBLIC ___dsk1_rdrnd

; /* ランダム読み出し(FCB) */
; uint8_t dsk1_rdrnd(void *fcb) __smallc;
dsk1_rdrnd:
_dsk1_rdrnd:
___dsk1_rdrnd:
    ld hl,2
    add hl,sp

    ld e,(hl)
    inc hl
    ld d,(hl)

    ld c,_RDRND
    jp BDOS_DSK