; /*********************************************************
;  dsk1_wrzer.asm mk_dskcallversion.sh によって自動生成されるファイルなので
;  書き換えないでください。

;   Do not rewrite dsk1_wrzer.asm as this file is
;  automatically generated by mk_dskcallversion.sh.

;  *********************************************************/

    include "msxlib/asm/msxdos.inc"


    SECTION code_user
    PUBLIC dsk1_wrzer
    PUBLIC _dsk1_wrzer
    PUBLIC ___dsk1_wrzer

; /* ゼロフィルを行うランダム書き込み(FCB) */
; uint8_t __LIB__ dsk1_wrzer(MSX_FCB *fcb) __smallc;
dsk1_wrzer:
_dsk1_wrzer:
___dsk1_wrzer:
    ld hl,2
    add hl,sp

    ld e,(hl)
    inc hl
    ld d,(hl)

    ld c,_WRZER
    jp BDOS_DSK
