; /*********************************************************
;  dsk1_login.asm mk_dskcallversion.sh によって自動生成されるファイルなので
;  書き換えないでください。

;   Do not rewrite dsk1_login.asm as this file is
;  automatically generated by mk_dskcallversion.sh.

;  *********************************************************/

    include "msxlib/asm/msxdos.inc"


    SECTION code_user
    PUBLIC dsk1_login
    PUBLIC _dsk1_login
    PUBLIC ___dsk1_login


; /* ログインベクタの取得 */
; uint16_t dsk1_login();
dsk1_login:
_dsk1_login:
___dsk1_login:
    ld c,_LOGIN
    jp BDOS_DSK
