; /*********************************************************
;  dsk1_bufin.asm mk_dskcallversion.sh によって自動生成されるファイルなので
;  書き換えないでください。

;   Do not rewrite dsk1_bufin.asm as this file is
;  automatically generated by mk_dskcallversion.sh.

;  *********************************************************/

    include "msxlib/asm/msxdos.inc"


    SECTION code_user
    PUBLIC dsk1_bufin
    PUBLIC _dsk1_bufin
    PUBLIC ___dsk1_bufin

; /* バッファ行入力 */
; void __LIB__ dsk1_bufin(char *buf) __smallc;
dsk1_bufin:
_dsk1_bufin:
___dsk1_bufin:
    ld hl,2
    add hl,sp

    ld e,(hl)
    inc hl
    ld d,(hl)
    
    ld c,_BUFIN
    jp BDOS_DSK
