; /*********************************************************
;  dsk2_pfile.asm mk_dskcallversion.sh によって自動生成されるファイルなので
;  書き換えないでください。

;   Do not rewrite dsk2_pfile.asm as this file is
;  automatically generated by mk_dskcallversion.sh.

;  *********************************************************/

    include "msxlib/asm/msxdos.inc"


    SECTION code_user
    PUBLIC dsk2_pfile
    PUBLIC _dsk2_pfile
    PUBLIC ___dsk2_pfile


; /* ファイル名の解析 */
; void dsk2_pfile(const char *filenmae, char *buf, char **last_str, uint8_t *analysis_flag);
dsk2_pfile:
_dsk2_pfile:
___dsk2_pfile:
    ld hl,6
    add hl,sp

    ld e,(hl)
    inc hl
    ld d,(hl)
    inc hl

    ld a,(hl)
    inc hl
    ld h,(hl)
    ld l,a

    ex hl,de

    ld c,_PFILE
    call BDOS_DSK

    ld hl,2
    add hl,sp
    
    push de
    ld e,(hl)
    inc hl
    ld d,(hl)
    inc hl

    ex hl,de
    ld (hl),b
    ex hl,de

    ld e,(hl)
    inc hl
    ld d,(hl)

    ex hl,de
    pop de
    
    ld (hl),e
    inc hl
    ld (hl),d    

    ret    
