; /*********************************************************
;  dsk2_close.asm mk_dskcallversion.sh によって自動生成されるファイルなので
;  書き換えないでください。

;   Do not rewrite dsk2_close.asm as this file is
;  automatically generated by mk_dskcallversion.sh.

;  *********************************************************/

    include "msxlib/asm/msxdos.inc"


    SECTION code_user
    PUBLIC dsk2_close
    PUBLIC _dsk2_close
    PUBLIC __dsk2_close


; /* ファイルハンドルのクローズ */
; uint8_t dsk2_close(uint8_t handle);
dsk2_close:
_dsk2_close:
__dsk2_close:
    ld hl,2
    add hl,sp

    ld b,(hl)

    ld c,_CLOSE
    call BDOS_DSK

    ld l,a
    
    ret