; /*********************************************************
;  dsk2_open.asm mk_dskcallversion.sh によって自動生成されるファイルなので
;  書き換えないでください。

;   Do not rewrite dsk2_open.asm as this file is
;  automatically generated by mk_dskcallversion.sh.

;  *********************************************************/


    include "msxlib/asm/msxdos.inc"


    SECTION code_user
    PUBLIC dsk2_open
    PUBLIC _dsk2_open
    PUBLIC ___dsk2_open


; /* ファイルハンドルのオープン */
; uint8_t __LIB__ dsk2_open(const char *filepath, uint8_t mode, uint8_t *handle) __smallc;
; sp + 2    handle
; sp + 4    mode
; sp + 6    filepath
dsk2_open:
_dsk2_open:
___dsk2_open:
    ld hl,4
    add hl,sp

    ; modeとりだし
    ld a,(hl)
    inc hl
    inc hl

    ; filepathの取り出し
    ld e,(hl)
    inc hl
    ld d,(hl)

    ld c,_OPEN
    call BDOS_DSK

    ld hl,2
    add hl,sp

    ld e,(hl)
    inc hl
    ld d,(hl)

    ex hl,de

    ld (hl),b

    ld l,a

    ret