; /*********************************************************
;  dsk2_dosver.asm mk_dskcallversion.sh によって自動生成されるファイルなので
;  書き換えないでください。

;   Do not rewrite dsk2_dosver.asm as this file is
;  automatically generated by mk_dskcallversion.sh.

;  *********************************************************/

    include "msxlib/asm/msxdos.inc"


    SECTION code_user
    PUBLIC dsk2_dosver
    PUBLIC _dsk2_dosver
    PUBLIC ___dsk2_dosver


; /* MSX-DOSのバーション番号の取得 */
; uint8_t dsk2_dosver(uint16_t *kernel_ver, uint16_t *dos_ver);
dsk2_dosver:
_dsk2_dosver:
___dsk2_dosver:
    ld c,_DOSVER
    call BDOS_DSK

    ld hl,2
    add hl,sp

    push de
    ld e,(hl)
    inc hl
    ld d,(hl)
    
    ex hl,de
    pop de
    
    ld (hl),e
    inc hl
    ld (hl),d

    ld hl,4
    add hl,sp

    ld e,(hl)
    inc hl
    ld d,(hl)

    ex hl,de

    ld (hl),c
    inc hl
    ld (hl),b

    ld l,a

    ret