; /*********************************************************
;  dsk2_fnext.asm mk_dskcallversion.sh によって自動生成されるファイルなので
;  書き換えないでください。

;   Do not rewrite dsk2_fnext.asm as this file is
;  automatically generated by mk_dskcallversion.sh.

;  *********************************************************/

    include "msxlib/asm/msxdos.inc"


    SECTION code_user
    PUBLIC dsk2_fnext
    PUBLIC _dsk2_fnext
    PUBLIC ___dsk2_fnext


; /* 次のエントリの検索 */
; uint8_t __LIB__ dsk2_fnext(MSX_FIB *fib) __smallc;

dsk2_fnext:
_dsk2_fnext:
___dsk2_fnext:
    ld hl,2
    add hl,sp
    
    push ix
    ld e,(hl)
    inc hl
    ld d,(hl)

    push de
    pop ix

    ld c,_FNEXT
    call BDOS_DSK
    pop ix

    ld l,a
    ret