/*********************************************************
 msxvdp_dos_draw_char.c は、mk_dosversion.sh によって自動生成されるファイルなので
 書き換えないでください。

  Do not rewrite msxvdp_dos_draw_char.c as this file is
 automatically generated by mk_dosversion.sh.

 *********************************************************/

#include <stdint.h>
#include <msxlib/vdp.h>
#include <msxlib/msxwork.h>

void __LIB__ msxvdp_dos_draw_char(int16_t x, int16_t y, char ch, uint8_t logi_op) __smallc
{
    MSXWORK_LOGOPR_VAL = logi_op;
    MSXWORK_GRPACX_VAL = x;
    MSXWORK_GRPACY_VAL = y;
    msxmain_dos_grpprt(ch);
}
