/*********************************************************
 bfile/bfile_fseek_dsk2.c mk_dskcallversion.sh によって自動生成されるファイルなので
 書き換えないでください。

  Do not rewrite bfile/bfile_fseek_dsk2.c as this file is
 automatically generated by mk_dskcallversion.sh.

 *********************************************************/

#include <msxlib/bfile.h>
#include <msxlib/msxdos.h>

int32_t __LIB__ bfile_fseek_dsk2(BFILE_DOS2 *fp, int32_t offset, int whence) __smallc
{
    uint8_t err;

    if(fp->update) {
        if(!bfile_flush_dsk2(fp)) {
            return 0;
        }
    }
    err = dsk2_seek(fp->handle, &offset, whence);
    if(err != 0) {
        fp->err = err;
        offset = 0;
    }
    fp->dirty = TRUE;
    return offset;
}