/*********************************************************
 bfile/bfile_open_dsk1.c mk_dskcallversion.sh によって自動生成されるファイルなので
 書き換えないでください。

  Do not rewrite bfile/bfile_open_dsk1.c as this file is
 automatically generated by mk_dskcallversion.sh.

 *********************************************************/

#include <stdio.h>
#include <msxlib/msxlib.h>
#include <msxlib/bfile.h>

BFILE_DOS1 __LIB__ *bfile_open_dsk1(const char *filename, uint8_t mode, int16_t buf_size) __smallc
{
    BFILE_DOS1 *fp = NULL;

    if(mode != BFILE_O_RDONLY && mode != BFILE_O_WRONLY && mode != BFILE_O_RDWR) {
        return NULL;
    }

    fp = bfile_malloc_dsk1(filename, buf_size);
    if(!fp) {
        return NULL;
    }
    uint8_t err = dsk1_fopen(&fp->fcb);
    if(err) {
        free(fp->buf);
        free(fp);
        return NULL;
    }
    fp->fcb.v1.record_size = 1;
    fp->fcb.v1.random_record = 0;
    fp->mode = mode;

    return fp;
}
