#!/bin/bash
echo "/*********************************************************" > $2
echo " $2 は、mk_dosversion.sh によって自動生成されるファイルなので" >> $2
echo " 書き換えないでください。" >> $2
echo  >> $2
echo "  Do not rewrite $2 as this file is" >> $2
echo " automatically generated by mk_dosversion.sh." >> $2
echo >> $2
echo " *********************************************************/" >> $2
echo  >> $2

sed -e 's/_dct_/_dos_/g' $1 >> $2